### ISSUE TITLE
Missing sipbuild

### ISSUE THREAD

**Issue by 22758330** [Ultimaker/libArcus#141]
Hallo,
libArcus 5.0.0 does not compile with Ubuntu 22.04 LTS 
=> ModuleNotFoundError: No module named 'sipbuild'

Installed software
- protobuf 3.17.1
- SIP 6.5.0
- python 3.10.4

mkdir build && cd build
cmake ..
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting BUILD_SHARED_LIBS to ON
-- Setting build type to 'Release' as none was specified.
-- Generating compile commands to /home/klemmh/cura5/libArcus-5.0.0/build/compile_commands.json
-- Setting POSITION_INDEPENDENT_CODE: ON
-- Setting C++17 support with extensions off and standard required
-- Found Protobuf: /usr/local/lib/libprotobuf.a (found suitable version "3.17.1", minimum required is "3.17.1") 
-- Enabling threading support for Arcus
-- Found Threads: TRUE  
-- Setting SKIP_BUILD_RPATH for target Arcus to FALSE
-- Setting BUILD_WITH_INSTALL_RPATH for target Arcus to FALSE
-- Setting INSTALL_RPATH_USE_LINK_PATH for target Arcus to TRUE
-- Setting install RPATH for target Arcus to $ORIGIN/;$ORIGIN/$<$<PLATFORM_ID:Linux>:usr/bin>;$ORIGIN/$<$<PLATFORM_ID:Linux>:usr/bin/lib>;$ORIGIN/$<$<PLATFORM_ID:Darwin>:../lib>
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Setting Python version to 3.10. Set Python_VERSION if you want to compile against an other version.
-- Found Python: /usr/bin/python3.10 (found suitable exact version "3.10.4") found components: Interpreter Development Development.Module Development.Embed 
-- Linking and building  against Python 3.10.4
-- Found SIP version: 6.5.0
-- Setting SKIP_BUILD_RPATH for target pyArcus to FALSE
-- Setting BUILD_WITH_INSTALL_RPATH for target pyArcus to FALSE
-- Setting INSTALL_RPATH_USE_LINK_PATH for target pyArcus to TRUE
-- Setting install RPATH for target pyArcus to $ORIGIN/;$ORIGIN/$<$<PLATFORM_ID:Linux>:usr/bin>;$ORIGIN/$<$<PLATFORM_ID:Linux>:usr/bin/lib>;$ORIGIN/$<$<PLATFORM_ID:Darwin>:../lib>;$ORIGIN/$<$<PLATFORM_ID:Darwin>:../Resources/lib/>;$ORIGIN/../../
-- Enabling threading support for pyArcus
-- SIP: Generating pyproject.toml
-- SIP: Generating source files
'/usr/bin/cmake' '-E' 'env' 'PYTHONPATH=::/home/klemmh/cura5/libArcus-5.0.0/build' '/home/klemmh/.local/bin/sip-build' '--pep484-pyi' '--no-protected-is-public'
Using the CMake builder
These bindings will be built: pyArcus.
Generating the source files
Generating the pyArcus bindings...
Generating the pyArcus .pyi file...
The project has been built.
-- SIP: Touching the source files
-- SIP: Collecting the generated source files
-- SIP: Collecting the user specified source files
-- SIP: Linking the interface target against the shared library
-- SIP: Installing Python module and PEP 484 file in /usr/lib/python3/dist-packages
-- Configuring done
-- Generating done
-- Build files have been written to: /home/klemmh/cura5/libArcus-5.0.0/build
klemmh@HP-Z400-Workstation:~/cura5/libArcus-5.0.0/build$ make -j4
[ 13%] Building CXX object CMakeFiles/Arcus.dir/src/MessageTypeStore.cpp.o
[ 13%] Building CXX object CMakeFiles/Arcus.dir/src/SocketListener.cpp.o
[ 13%] Built target pyArcus
[ 13%] Building CXX object CMakeFiles/Arcus.dir/src/Socket.cpp.o
[ 17%] Building CXX object CMakeFiles/Arcus.dir/src/PlatformSocket.cpp.o
[ 21%] Building CXX object CMakeFiles/Arcus.dir/src/Error.cpp.o
In file included from /home/klemmh/cura5/libArcus-5.0.0/src/Socket.cpp:20:
/home/klemmh/cura5/libArcus-5.0.0/src/Socket_p.h: In member function ‘void Arcus::Socket::Private::sendMessage(const MessagePtr&)’:
/home/klemmh/cura5/libArcus-5.0.0/src/Socket_p.h:365:50: warning: ‘int google::protobuf::MessageLite::ByteSize() const’ is deprecated: Please use ByteSizeLong() instead [-Wdeprecated-declarations]
  365 |         uint32_t message_size = message->ByteSize();
      |                                 ~~~~~~~~~~~~~~~~~^~
In file included from /usr/local/include/google/protobuf/generated_enum_util.h:36,
                 from /usr/local/include/google/protobuf/generated_enum_reflection.h:44,
                 from /usr/local/include/google/protobuf/generated_message_reflection.h:46,
                 from /usr/local/include/google/protobuf/message.h:122,
                 from /home/klemmh/cura5/libArcus-5.0.0/src/Socket_p.h:41,
                 from /home/klemmh/cura5/libArcus-5.0.0/src/Socket.cpp:20:
/usr/local/include/google/protobuf/message_lite.h:430:7: note: declared here
  430 |   int ByteSize() const { return internal::ToIntSize(ByteSizeLong()); }
      |       ^~~~~~~~
In file included from /home/klemmh/cura5/libArcus-5.0.0/src/Socket.cpp:20:
/home/klemmh/cura5/libArcus-5.0.0/src/Socket_p.h: In member function ‘void Arcus::Socket::Private::handleMessage(const std::shared_ptr<Arcus::Private::WireMessage>&)’:
/home/klemmh/cura5/libArcus-5.0.0/src/Socket_p.h:551:34: warning: ‘void google::protobuf::io::CodedInputStream::SetTotalBytesLimit(int, int)’ is deprecated: Please use the single parameter version of SetTotalBytesLimit(). The second parameter is ignored. [-Wdeprecated-declarations]
  551 |         stream.SetTotalBytesLimit(message_size_maximum, message_size_warning);
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/google/protobuf/message_lite.h:47,
                 from /usr/local/include/google/protobuf/generated_enum_util.h:36,
                 from /usr/local/include/google/protobuf/generated_enum_reflection.h:44,
                 from /usr/local/include/google/protobuf/generated_message_reflection.h:46,
                 from /usr/local/include/google/protobuf/message.h:122,
                 from /home/klemmh/cura5/libArcus-5.0.0/src/Socket_p.h:41,
                 from /home/klemmh/cura5/libArcus-5.0.0/src/Socket.cpp:20:
/usr/local/include/google/protobuf/io/coded_stream.h:403:8: note: declared here
  403 |   void SetTotalBytesLimit(int total_bytes_limit, int) {
      |        ^~~~~~~~~~~~~~~~~~
[ 26%] Linking CXX shared library libArcus.so
[ 26%] Built target Arcus
[ 39%] Building C object CMakeFiles/sip_pyArcus.dir/pyArcus/pyArcus/objmap.c.o
[ 39%] Building C object CMakeFiles/sip_pyArcus.dir/pyArcus/pyArcus/array.c.o
[ 43%] Building C object CMakeFiles/sip_pyArcus.dir/pyArcus/pyArcus/descriptors.c.o
[ 43%] Building C object CMakeFiles/sip_pyArcus.dir/pyArcus/pyArcus/int_convertors.c.o
In file included from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sipint.h:26,
                 from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/objmap.c:23:
/home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sip.h:62: warning: "SIP_VERSION" redefined
   62 | #define SIP_VERSION                 0x60500
      | 
<command-line>: note: this is the location of the previous definition
In file included from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sipint.h:26,
                 from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/int_convertors.c:24:
/home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sip.h:62: warning: "SIP_VERSION" redefined
   62 | #define SIP_VERSION                 0x60500
      | 
<command-line>: note: this is the location of the previous definition
In file included from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sipint.h:26,
                 from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/descriptors.c:22:
/home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sip.h:62: warning: "SIP_VERSION" redefined
   62 | #define SIP_VERSION                 0x60500
      | 
<command-line>: note: this is the location of the previous definition
In file included from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sipint.h:26,
                 from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/array.c:25:
/home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sip.h:62: warning: "SIP_VERSION" redefined
   62 | #define SIP_VERSION                 0x60500
      | 
<command-line>: note: this is the location of the previous definition
[ 47%] Building C object CMakeFiles/sip_pyArcus.dir/pyArcus/pyArcus/siplib.c.o
[ 52%] Building C object CMakeFiles/sip_pyArcus.dir/pyArcus/pyArcus/threads.c.o
[ 56%] Building C object CMakeFiles/sip_pyArcus.dir/pyArcus/pyArcus/voidptr.c.o
[ 60%] Building CXX object CMakeFiles/sip_pyArcus.dir/pyArcus/pyArcus/bool.cpp.o
[ 65%] Building CXX object CMakeFiles/sip_pyArcus.dir/pyArcus/pyArcus/sippyArcuspart0.cpp.o
In file included from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sipint.h:26,
                 from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/threads.c:22:
/home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sip.h:62: warning: "SIP_VERSION" redefined
   62 | #define SIP_VERSION                 0x60500
      | 
<command-line>: note: this is the location of the previous definition
In file included from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/siplib.c:30:
/home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sip.h:62: warning: "SIP_VERSION" redefined
   62 | #define SIP_VERSION                 0x60500
      | 
<command-line>: note: this is the location of the previous definition
In file included from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sipint.h:26,
                 from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/voidptr.c:25:
/home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sip.h:62: warning: "SIP_VERSION" redefined
   62 | #define SIP_VERSION                 0x60500
      | 
<command-line>: note: this is the location of the previous definition
[ 69%] Building CXX object CMakeFiles/sip_pyArcus.dir/pyArcus/pyArcus/sippyArcuspart1.cpp.o
In file included from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sipAPIpyArcus.h:10,
                 from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sippyArcuspart0.cpp:10:
/home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sip.h:62: warning: "SIP_VERSION" redefined
   62 | #define SIP_VERSION                 0x60500
      | 
<command-line>: note: this is the location of the previous definition
[ 73%] Building CXX object CMakeFiles/sip_pyArcus.dir/pyArcus/pyArcus/sippyArcuspart2.cpp.o
In file included from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sipAPIpyArcus.h:10,
                 from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sippyArcuspart1.cpp:10:
/home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sip.h:62: warning: "SIP_VERSION" redefined
   62 | #define SIP_VERSION                 0x60500
      | 
<command-line>: note: this is the location of the previous definition
In file included from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sipAPIpyArcus.h:10,
                 from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sippyArcuspart2.cpp:10:
/home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sip.h:62: warning: "SIP_VERSION" redefined
   62 | #define SIP_VERSION                 0x60500
      | 
<command-line>: note: this is the location of the previous definition
[ 78%] Building CXX object CMakeFiles/sip_pyArcus.dir/pyArcus/pyArcus/sippyArcuspart3.cpp.o
In file included from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sipAPIpyArcus.h:10,
                 from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sippyArcuspart3.cpp:10:
/home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sip.h:62: warning: "SIP_VERSION" redefined
   62 | #define SIP_VERSION                 0x60500
      | 
<command-line>: note: this is the location of the previous definition
[ 82%] Building CXX object CMakeFiles/sip_pyArcus.dir/pyArcus/pyArcus/sippyArcuspart4.cpp.o
In file included from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sipAPIpyArcus.h:10,
                 from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sippyArcuspart4.cpp:10:
/home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sip.h:62: warning: "SIP_VERSION" redefined
   62 | #define SIP_VERSION                 0x60500
      | 
<command-line>: note: this is the location of the previous definition
[ 86%] Building CXX object CMakeFiles/sip_pyArcus.dir/pyArcus/pyArcus/sippyArcuspart5.cpp.o
[ 91%] Building CXX object CMakeFiles/sip_pyArcus.dir/pyArcus/pyArcus/sippyArcuspart6.cpp.o
In file included from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sipAPIpyArcus.h:10,
                 from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sippyArcuspart5.cpp:10:
/home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sip.h:62: warning: "SIP_VERSION" redefined
   62 | #define SIP_VERSION                 0x60500
      | 
<command-line>: note: this is the location of the previous definition
In file included from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sipAPIpyArcus.h:10,
                 from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sippyArcuspart6.cpp:10:
/home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sip.h:62: warning: "SIP_VERSION" redefined
   62 | #define SIP_VERSION                 0x60500
      | 
<command-line>: note: this is the location of the previous definition
[ 95%] Building CXX object CMakeFiles/sip_pyArcus.dir/python/PythonMessage.cpp.o
[100%] Linking CXX shared library pyArcus.so
Using the CMake builder
These bindings will be built: pyArcus.
Generating the source files
Generating the pyArcus bindings...
Generating the pyArcus .pyi file...
The project has been built.
[100%] Built target sip_pyArcus
klemmh@HP-Z400-Workstation:~/cura5/libArcus-5.0.0/build$ sudo make install
Consolidate compiler generated dependencies of target Arcus
[ 26%] Built target Arcus
[ 26%] Built target pyArcus
Consolidate compiler generated dependencies of target sip_pyArcus
[ 30%] Building C object CMakeFiles/sip_pyArcus.dir/pyArcus/pyArcus/array.c.o
In file included from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sipint.h:26,
                 from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/array.c:25:
/home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sip.h:62: warning: "SIP_VERSION" redefined
   62 | #define SIP_VERSION                 0x60500
      | 
<command-line>: note: this is the location of the previous definition
[ 34%] Building C object CMakeFiles/sip_pyArcus.dir/pyArcus/pyArcus/descriptors.c.o
In file included from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sipint.h:26,
                 from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/descriptors.c:22:
/home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sip.h:62: warning: "SIP_VERSION" redefined
   62 | #define SIP_VERSION                 0x60500
      | 
<command-line>: note: this is the location of the previous definition
[ 39%] Building C object CMakeFiles/sip_pyArcus.dir/pyArcus/pyArcus/int_convertors.c.o
In file included from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sipint.h:26,
                 from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/int_convertors.c:24:
/home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sip.h:62: warning: "SIP_VERSION" redefined
   62 | #define SIP_VERSION                 0x60500
      | 
<command-line>: note: this is the location of the previous definition
[ 43%] Building C object CMakeFiles/sip_pyArcus.dir/pyArcus/pyArcus/objmap.c.o
In file included from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sipint.h:26,
                 from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/objmap.c:23:
/home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sip.h:62: warning: "SIP_VERSION" redefined
   62 | #define SIP_VERSION                 0x60500
      | 
<command-line>: note: this is the location of the previous definition
[ 47%] Building C object CMakeFiles/sip_pyArcus.dir/pyArcus/pyArcus/siplib.c.o
In file included from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/siplib.c:30:
/home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sip.h:62: warning: "SIP_VERSION" redefined
   62 | #define SIP_VERSION                 0x60500
      | 
<command-line>: note: this is the location of the previous definition
[ 52%] Building C object CMakeFiles/sip_pyArcus.dir/pyArcus/pyArcus/threads.c.o
In file included from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sipint.h:26,
                 from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/threads.c:22:
/home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sip.h:62: warning: "SIP_VERSION" redefined
   62 | #define SIP_VERSION                 0x60500
      | 
<command-line>: note: this is the location of the previous definition
[ 56%] Building C object CMakeFiles/sip_pyArcus.dir/pyArcus/pyArcus/voidptr.c.o
In file included from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sipint.h:26,
                 from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/voidptr.c:25:
/home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sip.h:62: warning: "SIP_VERSION" redefined
   62 | #define SIP_VERSION                 0x60500
      | 
<command-line>: note: this is the location of the previous definition
[ 60%] Building CXX object CMakeFiles/sip_pyArcus.dir/pyArcus/pyArcus/bool.cpp.o
[ 65%] Building CXX object CMakeFiles/sip_pyArcus.dir/pyArcus/pyArcus/sippyArcuspart0.cpp.o
In file included from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sipAPIpyArcus.h:10,
                 from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sippyArcuspart0.cpp:10:
/home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sip.h:62: warning: "SIP_VERSION" redefined
   62 | #define SIP_VERSION                 0x60500
      | 
<command-line>: note: this is the location of the previous definition
[ 69%] Building CXX object CMakeFiles/sip_pyArcus.dir/pyArcus/pyArcus/sippyArcuspart1.cpp.o
In file included from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sipAPIpyArcus.h:10,
                 from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sippyArcuspart1.cpp:10:
/home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sip.h:62: warning: "SIP_VERSION" redefined
   62 | #define SIP_VERSION                 0x60500
      | 
<command-line>: note: this is the location of the previous definition
[ 73%] Building CXX object CMakeFiles/sip_pyArcus.dir/pyArcus/pyArcus/sippyArcuspart2.cpp.o
In file included from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sipAPIpyArcus.h:10,
                 from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sippyArcuspart2.cpp:10:
/home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sip.h:62: warning: "SIP_VERSION" redefined
   62 | #define SIP_VERSION                 0x60500
      | 
<command-line>: note: this is the location of the previous definition
[ 78%] Building CXX object CMakeFiles/sip_pyArcus.dir/pyArcus/pyArcus/sippyArcuspart3.cpp.o
In file included from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sipAPIpyArcus.h:10,
                 from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sippyArcuspart3.cpp:10:
/home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sip.h:62: warning: "SIP_VERSION" redefined
   62 | #define SIP_VERSION                 0x60500
      | 
<command-line>: note: this is the location of the previous definition
[ 82%] Building CXX object CMakeFiles/sip_pyArcus.dir/pyArcus/pyArcus/sippyArcuspart4.cpp.o
In file included from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sipAPIpyArcus.h:10,
                 from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sippyArcuspart4.cpp:10:
/home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sip.h:62: warning: "SIP_VERSION" redefined
   62 | #define SIP_VERSION                 0x60500
      | 
<command-line>: note: this is the location of the previous definition
[ 86%] Building CXX object CMakeFiles/sip_pyArcus.dir/pyArcus/pyArcus/sippyArcuspart5.cpp.o
In file included from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sipAPIpyArcus.h:10,
                 from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sippyArcuspart5.cpp:10:
/home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sip.h:62: warning: "SIP_VERSION" redefined
   62 | #define SIP_VERSION                 0x60500
      | 
<command-line>: note: this is the location of the previous definition
[ 91%] Building CXX object CMakeFiles/sip_pyArcus.dir/pyArcus/pyArcus/sippyArcuspart6.cpp.o
In file included from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sipAPIpyArcus.h:10,
                 from /home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sippyArcuspart6.cpp:10:
/home/klemmh/cura5/libArcus-5.0.0/build/pyArcus/pyArcus/sip.h:62: warning: "SIP_VERSION" redefined
   62 | #define SIP_VERSION                 0x60500
      | 
<command-line>: note: this is the location of the previous definition
[ 95%] Linking CXX shared library pyArcus.so
Traceback (most recent call last):
  File "/home/klemmh/.local/bin/sip-build", line 5, in <module>
    from sipbuild.tools.build import main
ModuleNotFoundError: No module named 'sipbuild'
make[2]: *** [CMakeFiles/sip_pyArcus.dir/build.make:341: pyArcus.so] Fehler 1
make[2]: *** Datei „pyArcus.so“ wird gelöscht
make[1]: *** [CMakeFiles/Makefile2:140: CMakeFiles/sip_pyArcus.dir/all] Fehler 2
make: *** [Makefile:136: all] Fehler 2

**Comment by jellespijker** [comment]
See this comment.

https://github.com/Ultimaker/libSavitar/issues/42#issuecomment-1139892321

**Comment by alucryd** [comment]
@jellespijker sipbuild isn't missing, according to the above log 6.5.0 was found.

The same error happens on Arch Linux, with 6.6.2.

```
/home/alucryd/Packages/community/arcus/trunk/src/build/pyArcus/pyArcus/sippyArcuspart3.cpp:424:102: error: ‘sipName___delattr__’ was not declared in this scope; did you mean ‘sipName___setattr__’?
```

**Comment by jellespijker** [comment]
Can you try it with the latest commit of the CURA-9177_fix_CI_CT branch.

Make sure sip 6.5.1 is on the PYTHONPATH, because sip 6.6.* has a known issue with our current build script.

**Comment by jellespijker** [comment]
It is unlikely that we will put the resources in to fix the sipmacro.cmake to work with a version number higher then 6.5.1 in the next couple of months. There isn't an immediate need for an upgrade for us atm and we really need the time to work on other stuff.

I suggest that you use a virtual environment with sip 6.5.1 when running cmake configure.
Since SIP is only used to generate the source code.

PR's are welcome of course.

**Comment by jellespijker** [comment]
Relaties to Ultimaker/CuraEngine/#1675

**Comment by jellespijker** [comment]
@alucryd #143 in combination with ultimaker/cura#12544 should fix this issue and the troubles you have with having a sip version higher then 6.5.1 in the AUR repository.

I created a Conan build helper (https://github.com/Ultimaker/conan-ultimaker-index/blob/CURA-9365_fix_building_cura_main/recipes/sipbuildtool/conanfile.py), which essentially sets up a virtual environment in the build folder of libarcus/libsavitar/pynest2d, it will use the Conan package with CPython, but you could use the system executable. as well.
It will then install sip==6.5.1 in the virtual python environment, generate the C/C++ source code from the sip files, and remove itself again. Leaving only the generated source files, in `cmake-build-release/pyArcus/pyArcus` these files are then used by CMake.

Granted this isn't the most elegant solution, but I think this is the one most suitable for our new build process. Check the PR in Cura repo.

In order to compile Arcus and pyArcus the following steps would suffice:
Make sure Conan is installed and it is advised to use our configuration (https://github.com/Ultimaker/conan-config.git)
```
python -m pip install conan --upgrade
conan config init
conan config install https://github.com/Ultimaker/conan-config.git -a "-b CURA-9177_Fix_CI_CD"
```
At the very least use our JFrog Artifactory to obtain the the conan recipe's, for the tools such as sipbuild and umbase (https://github.com/Ultimaker/conan-ultimaker-index/)
```
conan remote add cura-ce https://ultimaker.jfrog.io/artifactory/api/conan/cura-community True
```

```
conan install . arcus/5.1.0-alpha+666@ultimaker/cura_9365 --build=missing --update
cd cmake-build-release
cmake --toolchain=conan/conan_toolchain.cmake ..
ninja
```

If libArcus is only needed to get Cura in the AUR, it might be best to follow the workflow provided in the PR  ultimaker/cura#12544. because deploying Cura and it's dependencies to userspace might be as simple as:
```
conan install cura/5.1.0@_/_ --build=missing --update -g deploy
```
